apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 1m
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo