apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: podinfo-mkl-lol
  namespace: default
spec:
  secretName: podinfo-mkl-lol-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: podinfo.mkl.lol
  dnsNames:
  - podinfo.mkl.lol
--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-mkl-lol
  namespace: default
spec:
  secretName: nginx-mkl-lol-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: nginx.mkl.lol
  dnsNames:
  - nginx.mkl.lol
