apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: certmanager
  namespace: cert-manager
resources:
- namespace.yaml
- source.yaml
- release.yaml
specs:
  dependsOn:
    - name: traefik
