apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: certmanager
  name: cert-manager
spec:
  dependsOn:
    - name: traefik
  resources:
  - namespace.yaml
  - source.yaml
  - release.yaml
