apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager
  namespace: cert-manager
resources:
- namespace.yaml
- source.yaml
- release.yaml
spec:
  dependsOn:
    - name: traefik
