apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: 'v1.9.1'
      sourceRef:
        kind: HelmRepository
        name: jetstack
  extraArgs:
    installCRDs: true
  releaseName: cert-manager