apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ingress
  namespace: default
spec:
  dependsOn:
    - name: certmanager
    - name: traefik
  resources:
    - ingress.yaml
    
    