apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: "~24"
  interval: 1h0m0s
  releaseName: traefik
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    logs:
      general:
        level: INFO
      access:
        enabled: true
    globalArguments: []
    service:
      type: NodePort
    ports:
      web:
        nodePort: 32080
        redirectTo: websecure
      websecure:
        nodePort: 32443
    persistence:
      enabled: true
