apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
resources:
  - traefik-deployment.yaml
  - traefik-service.yaml
  - traefik-dashboard-service.yaml  # Add this line to include the dashboard service
