apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: default
spec:
  releaseName: traefik
  chart:
    repository: https://traefik.github.io/charts
    name: traefik
    #version: <chart-version>  # Specify the version of the Traefik Helm chart you want to use

