apiVersion: v1
kind: Node
metadata:
  name: worker1
  labels:
    node-role.kubernetes.io/worker: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: worker2
  labels:
    node-role.kubernetes.io/worker: "true"
